version: '3.8'
services:
  archive-playlist:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: archive-playlist
    environment:
      CLIENT_ID: ${CLIENT_ID}
      CLIENT_SECRET: ${CLIENT_SECRET}
      REDIRECT_URI: ${REDIRECT_URI}
      DISCOVER_WEEKLY_ARCHIVE_ID: ${DISCOVER_WEEKLY_ARCHIVE_ID}
      DISCOVER_WEEKLY_ID: ${DISCOVER_WEEKLY_ID}
      RELEASE_RADAR_ARCHIVE_ID: ${RELEASE_RADAR_ARCHIVE_ID}
      RELEASE_RADAR_ID: ${RELEASE_RADAR_ID}
    restart: on-failure
    ports:
      - "8123:8123"